[package]
name = "kana-kanji"
version = "0.1.0"
authors = ["Ryosuke Hashimoto <is0024xx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"